template = "https://github.com/giellalt/template-lang-und"
rev_id = 272
template_sha = "f40ff07ea2383e4e83e8ad0ff88b795ceaf841e6"

[replacements]
__GLOTTOLOG_ID__ = "luok1236"
__REPO__ = "lang-luo"
__UND2C__ = "luo"
__UNDEFINED__ = "Luo (Kenya and Tanzania)"
__UND__ = "luo"
