template = "https://github.com/giellalt/template-lang-und"
rev_id = 276
template_sha = "c9932c142bad82b28a2c8b49e60ad8895a749b1e"

[replacements]
__GLOTTOLOG_ID__ = "luok1236"
__REPO__ = "lang-luo"
__UND2C__ = "luo"
__UNDEFINED__ = "Luo (Kenya and Tanzania)"
__UND__ = "luo"
