template = "https://github.com/giellalt/template-lang-und"
rev_id = 280
template_sha = "6beee360d8349c39749ac477719ead241493924c"

[replacements]
__GLOTTOLOG_ID__ = "luok1236"
__REPO__ = "lang-luo"
__UND2C__ = "luo"
__UNDEFINED__ = "Luo (Kenya and Tanzania)"
__UND__ = "luo"
