template = "https://github.com/giellalt/template-lang-und"
rev_id = 279
template_sha = "7e1364a63ae8dd7a44d168dead7dc395b65c35a3"

[replacements]
__GLOTTOLOG_ID__ = "luok1236"
__REPO__ = "lang-luo"
__UND2C__ = "luo"
__UNDEFINED__ = "Luo (Kenya and Tanzania)"
__UND__ = "luo"
